---
title: Daily Drawdown Report
subtitle: StockViz
editor_options:
  chunk_output_type: console
output: 
  html_document:
    theme: flatly
    highlight: tango
    self_contained: false
    lib_dir: rmdlib		
    toc: true
    includes:
        in_header: header-US.html
        after_body: ../footer.html
---

```{r dt_chunk, include=FALSE}

createdDate <- gsub(" 0", " ",format(Sys.Date(), "%B %d, %Y"))

```

---
date: `r createdDate`
---

```{r, calc_chunk, echo = FALSE, message = FALSE, warning = FALSE}

library(mongolite)
library('RODBC')
library('quantmod')
library('PerformanceAnalytics')
library('xtable')
library('knitr')
library('kableExtra')

options(stringsAsFactors = FALSE)
options("scipen"=100)

#source("C:/stockviz/r/config.r")
source("/mnt/hollandr/config.r")

collPtr <- mongo("dump", url="mongodb://holland:27017/EtfPortfolioDb")
con <- odbcDriverConnect(sprintf("Driver={ODBC Driver 17 for SQL Server};Server=%s;Database=%s;Uid=%s;Pwd=%s;", ldbserver, "StockVizUS2", ldbuser, ldbpassword), case = "nochange", believeNRows = TRUE)

asofDt<-as.Date(sqlQuery(con, "select max(time_stamp) from BHAV_EQ_TD")[[1]])

genTables <- function(symbols, startDate, endDate){
	numCalDays <- as.integer(endDate-startDate)
	ongoingDf <- data.frame(SYMBOL = "", FROM="", DEPTH = 0.0)
	recoveringDf <- data.frame(SYMBOL = "", FROM="", TROUGH="", DEPTH = 0.0, BOUNCE = 0.0)
	for(symb in symbols){
		sym <- trimws(symb)
		message(".", appendLF = F)
		pxSeries <- sqlQuery(con, sprintf("select time_stamp, c from BHAV_EQ_TD where symbol = '%s' and time_stamp >= '%s' and time_stamp <= '%s'", sym, startDate, endDate))
		message("/", appendLF = F)
		if(nrow(pxSeries) < 0.5*numCalDays) next
		if(last(pxSeries$time_stamp) != endDate) next

		pXts <- xts(pxSeries$c, as.Date(pxSeries$time_stamp))
		retXts <- dailyReturn(pXts)
		tdd <- table.Drawdowns(retXts, 10)
		
		notRec <- tdd[is.na(tdd$Recovery),]
		if(nrow(notRec) > 0) {
			ongoingDf <- rbind(ongoingDf, c(toString(sym), toString(notRec$From[1]), notRec$Depth[1]))
		}
		
		recovering <- notRec[!is.na(notRec$Trough) & notRec$Trough < endDate,]
		if(nrow(recovering) > 0) {
			deepest <- recovering[order(recovering$Depth),][1,]
			fromDt <- as.Date(deepest$Trough[1])
			bounce <- Return.cumulative(retXts[sprintf("%s/%s", fromDt, endDate)])
			
			if (bounce > 0)	recoveringDf <- rbind(recoveringDf, c(toString(sym), toString(deepest$From[1]), toString(fromDt), deepest$Depth[1], bounce))
		}
	}
	
	ongoingDf <- ongoingDf[-1,]
	recoveringDf <- recoveringDf[-1,]
	
	ongoingDf$DEPTH <- 100*as.numeric(ongoingDf$DEPTH)
	recoveringDf$DEPTH <- 100*as.numeric(recoveringDf$DEPTH)
	recoveringDf$BOUNCE <- round(100*as.numeric(recoveringDf$BOUNCE), 2)
	
	ongoingDf <- ongoingDf[order(ongoingDf$DEPTH),]
	recoveringDf <- recoveringDf[order(recoveringDf$BOUNCE, decreasing = T),]
	
	return(list(ongoingDf, recoveringDf))
}
```

# Introduction

*Ongoing* drawdowns are a list of stocks that are yet to recover from their worst drawdowns. These are stocks that are yet to find their bottom, given the time-frame.

The list of *Recovering* stocks are those that have bounced back from their deepest drawdown during the given time-frame.

```{r, index_chunk, echo = FALSE, results='asis', message = FALSE, warning = FALSE}

indices <- c('XLG', 'XMHQ', 'JKJ')
indexNames <- c('S&P 500 Top 50', 'S&P MidCap 400 Quality', 'Morningstar Small Core')

generateReport <- function(startDate){
	cat("#", toString(startDate), "through", toString(asofDt), "\n")
	kableTable <- list()
	kableTable2 <- list()

	isOngoingEmpty <- TRUE
	isRecoveringEmpty <- TRUE
	for(i in 1:length(indices)){
		iName <- indices[i]
		message(iName)
		
		asof <- collPtr$aggregate(sprintf('[{ "$match" : { "etfTicker" : "%s" } }, { "$group": { "_id": "etfTicker", "updated": { "$max": "$portfolioDate" }} }]', iName))$updated
		message(asof)
		prot <- collPtr$find(query=sprintf('{ "etfTicker": "%s", "portfolioDate": { "$gte" : { "$date": "%sT00:00:00Z" }}}', iName, as.Date(asof)), fields='{"portfolio": true}')
		
		details<-prot$portfolio[[1]]
		detailsName <- names(details)
		if ("AssetType" %in% detailsName && "Holding Ticker" %in% detailsName) {
			syms <- details[details$AssetType == "equity", 'Holding Ticker']
		} else if ("AssetType" %in% detailsName && "Ticker" %in% detailsName) {
			syms <- details[details$AssetType == "equity", ]$Ticker
		} else if ("AssetType" %in% detailsName && "Identifier" %in% detailsName){
			syms <- details[details$AssetType == "equity", ]$Identifier
		} else {
			syms <- details[details$AssetClass == "Equity", ]$Ticker
		}
		
		message(length(syms))
		
		ddRet <- genTables(syms, startDate, asofDt)
		
		ongoingDD <- ddRet[[1]]
		recoveringDD <- ddRet[[2]]
		
		if(nrow(ongoingDD) > 0 && isOngoingEmpty == TRUE) isOngoingEmpty <- FALSE
		
		if(nrow(recoveringDD) > 0 && isRecoveringEmpty == TRUE) isRecoveringEmpty <- FALSE

		kableTable[[i]] <- kable(ongoingDD, align='llr', row.names = F, format.args = list(nsmall=2)) %>%
			kable_styling(bootstrap_options = c("condensed", "striped")) %>%
			scroll_box(height = "500px")
			
		kableTable2[[i]] <- kable(recoveringDD, align='lllrr', row.names = F, format.args = list(nsmall=2)) %>%
			kable_styling(bootstrap_options = c("condensed", "striped")) %>%
			scroll_box(height = "500px")
	}

	cat("## Ongoing\n")
	if(isOngoingEmpty){
		cat("No ongoing drawdowns\n")
	} else {
		for(i in 1:length(indexNames)){
			cat("###", indexNames[i], "\n")
			cat(kableTable[[i]])
		}
	}

	cat("## Recovering\n")
	if(isRecoveringEmpty){
		cat("No recovering drawdowns\n")
	} else {
		for(i in 1:length(indexNames)){
			cat("###", indexNames[i], "\n")
			cat(kableTable2[[i]])
		}
	}
}

generateReport(asofDt - 365)
generateReport(asofDt - 2*365)
```